#!/usr/bin/env python3
"""
MUSAEUS — Interactive Setup Wizard

First-run configuration: prompts for vault path and API keys,
writes ~/.config/musaeus/settings.env, creates vault directories,
and verifies system dependencies.

Usage:  musaeus setup
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


_CONFIG_DIR = Path.home() / ".config" / "musaeus"
_SETTINGS_FILE = _CONFIG_DIR / "settings.env"
_CREDENTIALS_FILE = _CONFIG_DIR / "credentials.env"

# ANSI helpers
_BOLD = "\033[1m" if sys.stdout.isatty() else ""
_GREEN = "\033[32m" if sys.stdout.isatty() else ""
_YELLOW = "\033[33m" if sys.stdout.isatty() else ""
_RED = "\033[31m" if sys.stdout.isatty() else ""
_CYAN = "\033[36m" if sys.stdout.isatty() else ""
_RST = "\033[0m" if sys.stdout.isatty() else ""


def _ok(msg: str) -> None:
    print(f"  {_GREEN}✓{_RST} {msg}")


def _warn(msg: str) -> None:
    print(f"  {_YELLOW}⚠{_RST} {msg}")


def _err(msg: str) -> None:
    print(f"  {_RED}✗{_RST} {msg}")


def _prompt(label: str, default: str = "") -> str:
    """Prompt with optional default shown in brackets."""
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"  {label}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    return val or default


def _check_binary(name: str) -> bool:
    """Check if a binary is on PATH."""
    return shutil.which(name) is not None


def cmd_setup() -> int:
    """Interactive setup wizard for MUSAEUS."""
    print()
    print(f"  {_CYAN}{_BOLD}╔══════════════════════════════════════════════════╗{_RST}")
    print(f"  {_CYAN}{_BOLD}║  MUSAEUS — First-Run Setup                       ║{_RST}")
    print(f"  {_CYAN}{_BOLD}╚══════════════════════════════════════════════════╝{_RST}")
    print()
    print("  This wizard will configure your vault path, check dependencies,")
    print("  and optionally set up API keys for enrichment features.")
    print()

    # ── Step 1: Vault Root ────────────────────────────────────────────────────
    print(f"  {_BOLD}Step 1/4: Vault Location{_RST}")
    print("  The vault is where MUSAEUS stores your music library, database,")
    print("  and all pipeline outputs.")
    print()

    existing_vault = os.environ.get("MUSAEUS_VAULT_ROOT", "")
    default_vault = existing_vault or "/mnt/FORGE2TB/Projects/MUSAEUS_VAULT"
    vault_path = _prompt("Vault root path", default_vault)

    if not vault_path:
        _err("Vault path is required. Aborting.")
        return 1

    vault = Path(vault_path).resolve()
    print()

    # ── Step 2: API Keys ──────────────────────────────────────────────────────
    print(f"  {_BOLD}Step 2/4: API Keys (optional){_RST}")
    print("  Last.fm key enables genre enrichment via the Enrich stage.")
    print("  Get one free at: https://www.last.fm/api/account/create")
    print()

    existing_lastfm = os.environ.get("LASTFM_API_KEY", "")
    lastfm_key = _prompt("Last.fm API key (blank to skip)", existing_lastfm)
    print()

    # ── Step 3: Write Config ──────────────────────────────────────────────────
    print(f"  {_BOLD}Step 3/4: Write Configuration{_RST}")

    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # settings.env
    settings_lines = [
        "# MUSAEUS configuration — generated by musaeus setup",
        f"MUSAEUS_VAULT_ROOT={vault}",
        f"MUSAEUS_DB_PATH={vault / 'musaeus.db'}",
        f"MUSAEUS_INBOX={vault / 'INBOX'}",
        f"MUSAEUS_RUNS_ROOT={vault / 'RUNS'}",
        f"MUSAEUS_META_DIR={vault / 'MetaData'}",
    ]
    _SETTINGS_FILE.write_text("\n".join(settings_lines) + "\n", encoding="utf-8")
    _ok(f"Written: {_SETTINGS_FILE}")

    # credentials.env (only if keys provided)
    if lastfm_key:
        cred_lines = [
            "# MUSAEUS credentials — generated by musaeus setup",
            f"LASTFM_API_KEY={lastfm_key}",
        ]
        _CREDENTIALS_FILE.write_text("\n".join(cred_lines) + "\n", encoding="utf-8")
        # Restrict permissions on credentials
        _CREDENTIALS_FILE.chmod(0o600)
        _ok(f"Written: {_CREDENTIALS_FILE} (mode 600)")
    else:
        _warn("No API keys configured — Enrich stage will be a no-op.")

    # ── Step 4: Create Directories & Check Deps ───────────────────────────────
    print()
    print(f"  {_BOLD}Step 4/4: System Check{_RST}")

    # Create vault directories
    dirs = [
        vault,
        vault / "INBOX",
        vault / "STAGING",
        vault / "QUARANTINE",
        vault / "RUNS",
        vault / "MetaData",
        vault / "Noise",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    _ok(f"Vault directories created: {vault}")

    # Create default canon files if missing
    canon_dir = vault / "MetaData"
    artist_canon = canon_dir / "artist_canon.tsv"
    genre_allowed = canon_dir / "genre_allowed.txt"
    genre_map = canon_dir / "genre_map.tsv"

    if not artist_canon.exists():
        artist_canon.write_text(
            "# Artist Canon — raw_name<TAB>canonical_name\n"
            "# Add entries as: the beatles\tThe Beatles\n",
            encoding="utf-8",
        )
        _ok("Created: artist_canon.tsv (empty template)")

    if not genre_allowed.exists():
        genre_allowed.write_text(
            "# Allowed genres — one per line\n"
            "Rock\n"
            "Pop\n"
            "Electronic\n"
            "Hip-Hop\n"
            "Jazz\n"
            "Classical\n"
            "Metal\n"
            "R&B\n"
            "Country\n"
            "Folk\n"
            "Blues\n"
            "Ambient\n"
            "Soul\n"
            "Funk\n"
            "Punk\n"
            "Reggae\n"
            "Latin\n"
            "World\n"
            "Soundtrack\n"
            "New Age\n",
            encoding="utf-8",
        )
        _ok("Created: genre_allowed.txt (20 common genres)")

    if not genre_map.exists():
        genre_map.write_text(
            "# Genre Map — raw_genre<TAB>canonical_genre\n"
            "hip-hop/rap\tHip-Hop\n"
            "electronica\tElectronic\n"
            "hard rock\tRock\n"
            "trip hop\tElectronic\n"
            "alternative rock\tRock\n"
            "indie rock\tRock\n"
            "rhythm and blues\tR&B\n"
            "r&b/soul\tR&B\n",
            encoding="utf-8",
        )
        _ok("Created: genre_map.tsv (common mappings)")

    # Check system dependencies
    print()
    deps_ok = True

    if _check_binary("ffmpeg"):
        _ok("ffmpeg    : found")
    else:
        _err("ffmpeg    : NOT FOUND — install with: sudo apt install ffmpeg")
        deps_ok = False

    if _check_binary("ffprobe"):
        _ok("ffprobe   : found")
    else:
        _err("ffprobe   : NOT FOUND — comes with ffmpeg package")
        deps_ok = False

    if _check_binary("fpcalc"):
        _ok("fpcalc    : found (acoustic fingerprinting available)")
    else:
        _warn("fpcalc    : not found — install with: sudo apt install libchromaprint-tools")
        _warn("            (optional — only needed for acoustic dedupe)")

    # Check mutagen
    try:
        import mutagen  # noqa: F401
        _ok("mutagen   : found")
    except ImportError:
        _err("mutagen   : NOT FOUND — install with: pip install mutagen")
        deps_ok = False

    # ── Summary ───────────────────────────────────────────────────────────────
    print()
    print(f"  {'─' * 50}")
    if deps_ok:
        _ok(f"{_BOLD}Setup complete!{_RST}")
        print()
        print("  Next steps:")
        print(f"    1. Drop audio files into: {vault / 'INBOX'}")
        print("    2. Run the pipeline:       musaeus run --full")
        print("    3. Or launch the console:  musaeus")
    else:
        _warn(f"{_BOLD}Setup complete with warnings.{_RST}")
        print("  Fix the missing dependencies above, then run: musaeus setup")

    print()
    return 0
