#!/usr/bin/env python3
"""
MUSAEUS — Curator Stage

Builds a car-library export from CATALOGUED files.
Copies audio files into a structured export tree:
    <export_root>/<Artist>/<Album>/<track> - <title>.<ext>

Noise profiles (optional):
  - clean   : no noise tracks
  - pink    : copy Pink_Noise_30min.m4a  (if present in vault)
  - brown   : copy Brown_Noise_60min.m4a
  - dual    : both pink + brown  (default)
  - white   : White_Noise_30min.m4a

Export path and noise variant are stored in archive.car_export_path /
archive.noise_profile.

Rules:
  - dry_run() reports what would be copied — no actual file I/O.
  - Already-exported files whose source hasn't changed are skipped.
  - Destination structure is created as needed.
  - Periodic DB commits every _COMMIT_EVERY files.
"""

from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path

from ..context import RunContext, StageResult
from .base import BaseStage, StageError

logger = logging.getLogger(__name__)

_COMMIT_EVERY = 100

# Ensemble/duo names that must never be split at " & " for folder naming.
_PROTECTED_ARTIST_NAMES: frozenset[str] = frozenset(
    {
        "crosby, stills & nash",
        "crosby, stills, nash & young",
        "earth, wind & fire",
        "simon & garfunkel",
        "hall & oates",
        "sly & the family stone",
        "adam & the ants",
        "barney bentall & the legendary hearts",
        "of monsters and men",
        "big brother & the holding company",
        "dr. hook & the medicine show",
    }
)

_FEAT_RE = re.compile(
    r"\s+(?:feat\.?|featuring|ft\.?|with|duet with|vs\.?|versus)\s+",
    re.IGNORECASE,
)


def _primary_artist(raw: str) -> str:
    """Strip collaborator tail and return first/primary artist name for folder use."""
    name = (raw or "Unknown Artist").strip()
    if name.lower() in _PROTECTED_ARTIST_NAMES:
        return name
    name = _FEAT_RE.split(name, 1)[0].strip()
    if name.lower() in _PROTECTED_ARTIST_NAMES:
        return name
    if ";" in name:
        name = name.split(";", 1)[0].strip()
    if name.lower() in _PROTECTED_ARTIST_NAMES:
        return name
    if " & " in name:
        name = name.split(" & ", 1)[0].strip()
    if name.lower() in _PROTECTED_ARTIST_NAMES:
        return name
    if " - " in name:
        parts = [p.strip() for p in name.split(" - ") if p.strip()]
        if len(parts) >= 2:
            name = parts[0]
    if name.lower() in _PROTECTED_ARTIST_NAMES:
        return name
    # Only a real collaborator credit if the text after the first comma
    # isn't an article (the/a/an, case-insensitive) -- "Beatles, The" is
    # the confirmed real on-disk canonical suffix form, not a
    # collaborator credit, and must survive this step untouched. Same
    # fix as artist_consolidate.py's _strip_collaborator_tail() -- this
    # function had the identical bug (dropped the article, produced
    # "Beatles" as the car-export folder name for a ", The" artist).
    if "," in name:
        head, _, tail = name.partition(",")
        if tail.strip().lower() not in ("the", "a", "an"):
            name = head.strip()
    return name or "Unknown Artist"


# Noise track filenames (generated by musaeus noise-gen or copied manually)
NOISE_FILES: dict[str, list[str]] = {
    "pink": ["Pink_Noise_30min.m4a", "Pink_Noise_60min.m4a"],
    "brown": ["Brown_Noise_60min.m4a", "Brown_Noise_30min.m4a"],
    "white": ["White_Noise_30min.m4a", "White_Noise_60min.m4a"],
}
NOISE_SUBDIR = "Acoustic Treatment"  # subfolder inside export root


def _sanitise(name: str) -> str:
    """Make a string safe for use as a path component."""
    # Windows-safe: strip chars illegal on FAT/NTFS/exFAT
    illegal = r'\/:*?"<>|'
    for ch in illegal:
        name = name.replace(ch, "_")
    return name.strip().strip(".")[:120] or "_unknown_"


def _dest_path(export_root: Path, row: dict, noise_subdir: bool = False) -> Path:
    """Compute the destination file path for one archive row."""
    artist = _sanitise(_primary_artist(row.get("artist") or "Unknown Artist"))
    album = _sanitise(row.get("album") or "Unknown Album")
    ext = (row.get("ext") or ".m4a").lower()
    if not ext.startswith("."):
        ext = "." + ext

    track = row.get("track")
    title = _sanitise(row.get("title") or Path(row["file_path"]).stem)

    filename = f"{int(track):02d} - {title}{ext}" if track else f"{title}{ext}"

    return export_root / artist / album / filename


class CuratorStage(BaseStage):
    """
    Assemble a car-library export from the catalogued archive.

    Configuration via ctx stash:
        ctx.set("curator_export_root", Path("/mnt/USB"))
        ctx.set("curator_noise",       "dual")   # clean|pink|brown|white|dual
        ctx.set("curator_force",       False)     # re-copy even if unchanged
    """

    NAME = "curator"

    def validate(self, ctx: RunContext) -> None:
        export_root = self._get_export_root(ctx)
        if export_root is None:
            raise StageError(
                "No export root set. "
                "Pass --export-root or: ctx.set('curator_export_root', Path(...))"
            )
        # Don't require it to exist yet — we'll create it.

    # ── helpers ───────────────────────────────────────────────────────────────

    def _get_export_root(self, ctx: RunContext) -> Path | None:
        raw = ctx.get("curator_export_root")
        if raw is None:
            # Fall back to config if present
            cfg_root = getattr(ctx.config, "car_export_root", None)
            if cfg_root:
                return Path(cfg_root)
            return None
        return Path(raw)

    def _get_noise_mode(self, ctx: RunContext) -> str:
        return str(ctx.get("curator_noise", "dual"))

    def _get_pending(self, ctx: RunContext, force: bool) -> list[dict]:
        if force:
            rows = ctx.conn.execute(
                """
                SELECT file_path, artist, album, title, track, ext, audio_hash
                  FROM archive
                 WHERE status = 'CATALOGUED'
                 ORDER BY artist, album, track
                """
            ).fetchall()
        else:
            rows = ctx.conn.execute(
                """
                SELECT file_path, artist, album, title, track, ext, audio_hash
                  FROM archive
                 WHERE status = 'CATALOGUED'
                   AND (car_export_path IS NULL OR car_export_path = '')
                 ORDER BY artist, album, track
                """
            ).fetchall()
        return [dict(r) for r in rows]

    def _find_noise_files(self, ctx: RunContext) -> list[Path]:
        """Locate noise track files in the vault."""
        vault = ctx.vault_root
        noise_dir = vault / "Noise"
        found: list[Path] = []
        for p in [vault, noise_dir]:
            if p.exists():
                for f in p.rglob("*.m4a"):
                    found.append(f)
        return found

    def _select_noise_files(self, noise_mode: str, all_noise: list[Path]) -> list[Path]:
        """Filter noise files by mode."""
        if noise_mode == "clean":
            return []
        keywords = []
        if noise_mode in NOISE_FILES:
            keywords = [kw.lower() for kw in NOISE_FILES[noise_mode]]
        elif noise_mode == "dual":
            keywords = ["pink", "brown"]
        else:
            keywords = []

        if not keywords:
            return all_noise  # 'all' mode
        return [f for f in all_noise if any(kw in f.stem.lower() for kw in keywords)]

    def _copy_file(self, src: Path, dst: Path) -> bool:
        """Copy src → dst, creating parent dirs. Returns True on success.
        Guards against TOCTOU race: file may vanish between exists() check and copy."""
        try:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(src), str(dst))
            return True
        except FileNotFoundError:
            logger.warning("curator: source vanished before copy: %s", src)
            return False
        except Exception as exc:
            logger.warning("curator copy failed %s → %s: %s", src, dst, exc)
            return False

    def _save_export_path(
        self, ctx: RunContext, file_path: str, dest: Path, noise_profile: str
    ) -> None:
        ctx.conn.execute(
            """
            UPDATE archive
               SET car_export_path = ?,
                   noise_profile   = ?
             WHERE file_path = ?
            """,
            (str(dest), noise_profile, file_path),
        )
        ctx.log_event(
            "CURATOR_COPY",
            file_path=file_path,
            new_value=str(dest),
            stage="curator",
        )

    # ── run ───────────────────────────────────────────────────────────────────

    def run(self, ctx: RunContext) -> StageResult:
        result = self._make_result(dry_run=False)
        export_root = self._get_export_root(ctx)
        noise_mode = self._get_noise_mode(ctx)
        force: bool = ctx.get("curator_force", False)

        export_root.mkdir(parents=True, exist_ok=True)  # type: ignore[union-attr]

        pending = self._get_pending(ctx, force)
        total = len(pending)
        result.notes.append(f"files to export : {total}")
        result.notes.append(f"export root     : {export_root}")
        result.notes.append(f"noise mode      : {noise_mode}")

        copied = 0
        skipped = 0
        errors = 0

        for i, row in enumerate(pending, 1):
            src = Path(row["file_path"])
            if not src.exists():
                result.files_skipped += 1
                skipped += 1
                continue

            dst = _dest_path(export_root, row)  # type: ignore[arg-type]

            # Skip if dest already exists and is same size (idempotent)
            if not force and dst.exists() and dst.stat().st_size == src.stat().st_size:
                result.files_skipped += 1
                skipped += 1
                self._save_export_path(ctx, row["file_path"], dst, noise_mode)
                continue

            ok = self._copy_file(src, dst)
            result.files_processed += 1
            if ok:
                result.files_changed += 1
                copied += 1
                self._save_export_path(ctx, row["file_path"], dst, noise_mode)
            else:
                result.files_errored += 1
                errors += 1

            if i % _COMMIT_EVERY == 0:
                ctx.conn.commit()
                logger.info("curator: checkpoint %d/%d", i, total)

        # Noise tracks
        if noise_mode != "clean":
            all_noise = self._find_noise_files(ctx)
            noise_files = self._select_noise_files(noise_mode, all_noise)
            noise_dest_dir = export_root / NOISE_SUBDIR  # type: ignore[operator]
            for nf in noise_files:
                dst = noise_dest_dir / nf.name
                if not dst.exists():
                    ok = self._copy_file(nf, dst)
                    if ok:
                        result.notes.append(f"  noise: {nf.name}")
                    else:
                        result.notes.append(f"  noise FAILED: {nf.name}")
            if not noise_files:
                result.notes.append(
                    f"  noise: no files found for mode '{noise_mode}' "
                    "(place them in <vault>/Noise/)"
                )

        ctx.conn.commit()

        result.notes.append(f"  copied  : {copied}")
        result.notes.append(f"  skipped : {skipped}")
        if errors:
            result.notes.append(f"  errors  : {errors}")
            result.success = False

        ctx.record_stage(result)
        return result

    # ── dry_run ───────────────────────────────────────────────────────────────

    def dry_run(self, ctx: RunContext) -> StageResult:
        result = self._make_result(dry_run=True)
        export_root = self._get_export_root(ctx)
        noise_mode = self._get_noise_mode(ctx)
        force: bool = ctx.get("curator_force", False)

        pending = self._get_pending(ctx, force)
        total = len(pending)

        would_copy = 0
        would_skip = 0
        for row in pending:
            src = Path(row["file_path"])
            if not src.exists():
                would_skip += 1
                continue
            dst = _dest_path(export_root, row)  # type: ignore[arg-type]
            if not force and dst.exists() and dst.stat().st_size == src.stat().st_size:
                would_skip += 1
            else:
                would_copy += 1

        noise_count = len(self._select_noise_files(noise_mode, self._find_noise_files(ctx)))

        result.files_processed = total
        result.files_changed = would_copy
        result.files_skipped = would_skip
        result.notes.append(f"[DRY RUN] export root : {export_root}")
        result.notes.append(f"[DRY RUN] noise mode  : {noise_mode} ({noise_count} file(s) found)")
        result.notes.append(f"[DRY RUN] would copy  : {would_copy}")
        result.notes.append(f"[DRY RUN] already ok  : {would_skip}")

        ctx.record_stage(result)
        return result
